version: 2
jobs:
  test:
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - run: ./gradlew clean test --stacktrace --info
    
    environment:
       AWS_ACCESS_KEY_ID     =
       AWS_SECRET_ACCESS_KEY =
       AWS_DEFAULT_REGION    = us-east-2
       AWS_ACCOUNT_ID        = 
       AWS_ECR_ACCOUNT_URL   =
       
  deploy:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - run: 
          name: Build image and push
          command: ./package.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
